services:
  - type: web
    name: carta-da-maria
    env: docker            # usa o Dockerfile da raiz
    plan: free
    region: virginia       # melhor latência para o Brasil
    autoDeploy: true

    # Health check simples
    healthCheckPath: /
    healthCheckTimeout: 30

    # Variáveis de ambiente
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://seu-subdominio.onrender.com
      - key: APP_KEY
        value: base64:COLE_AQUI_SUA_APP_KEY
      # Opcional — manter o texto da carta no env:
      # - key: CARTA_TEXTO
      #   value: "Seu texto lindo aqui ❤️ com quebras de linha\nfuncionando"

    # Escalonamento (Free = 1 instância)
    numInstances: 1
